# Generated by Django 2.2 on 2021-08-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_problemreported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreported',
            options={'verbose_name': 'Problem Reported', 'verbose_name_plural': 'Problems Reported'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('created',)},
        ),
    ]
